[build]
  command = "yarn build"
  publish = "dist/client"
  functions = "dist/server"

[[redirects]]
  from = "/trendTech.json"
  to = "/.netlify/functions/trendTech"

[[redirects]]
  from = "/trendIdea.json"
  to = "/.netlify/functions/trendIdea"

[[redirects]]
  from = "/trendBook.json"
  to = "/.netlify/functions/trendBook"

[[redirects]]
  from = "/trend"
  to = "/"